; 主机工程 - 负责上位机通信 + 主从通信
[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube

build_flags = 
    -D USE_HAL_DRIVER
    -D STM32F103xB
    -D HSE_VALUE=8000000U
